/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ReservationController;
import Controller.VehicleController;
import DAO.VehicleDAO;
import DataBase.DBConnection;
import Model.Reservation;
import Model.Session;
import Model.Vehicle;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kaleb
 */
public class CustomerDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form CustomerDashBoard
     */
    public CustomerDashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVehicles1 = new javax.swing.JTable();
        txtModelSearch1 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        txtVehicleId = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        txtVehicleModel = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblReservations = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehicles = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        txtModelSearch2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        SearchTbl = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtReturnDate = new javax.swing.JTextField();
        txtReserveDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtVehId = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        reservation = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 51));
        jPanel1.setForeground(new java.awt.Color(0, 255, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 255, 0));
        jButton1.setText("View Vehicle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 119, 140, 41));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 255, 0));
        jButton2.setText("Search Vihecle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 198, 140, 40));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 255, 51));
        jButton3.setText("Reserve a Vehicle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 347, 140, 38));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 255, 51));
        jButton4.setText("Calncle Reservation");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 418, 140, 40));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 255, 0));
        jButton6.setText("View Vehcle Price");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, 37));

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(0, 204, 0));
        jButton5.setText("LogOut");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 90, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Abbisinya Rental ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 320, 27));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Your journey, our wheels.");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 350, 40));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVehicles1.setBackground(new java.awt.Color(0, 204, 0));
        tblVehicles1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "VehicleId", "Model", "PlateNo", "DailyPrice"
            }
        ));
        jScrollPane3.setViewportView(tblVehicles1);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 390, 317));

        txtModelSearch1.setBackground(new java.awt.Color(0, 204, 51));
        txtModelSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelSearch1ActionPerformed(evt);
            }
        });
        jPanel5.add(txtModelSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 191, -1));

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("View Price");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Vihecle Model");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 140, 32));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/okcc1.png"))); // NOI18N
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -50, 960, 560));

        jTabbedPane1.addTab("", jPanel5);
        jTabbedPane1.addTab("", jTabbedPane2);

        txtVehicleId.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setBackground(new java.awt.Color(0, 204, 0));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Calcle reservation");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        txtVehicleId.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 183, 30));

        jButton13.setBackground(new java.awt.Color(0, 153, 0));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Enter Vehicle Model");
        txtVehicleId.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtVehicleModel.setBackground(new java.awt.Color(0, 204, 51));
        txtVehicleModel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtVehicleModel.setForeground(new java.awt.Color(0, 0, 0));
        txtVehicleModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleModelActionPerformed(evt);
            }
        });
        txtVehicleId.add(txtVehicleModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 194, -1));

        tblReservations.setBackground(new java.awt.Color(0, 204, 51));
        tblReservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Reservation ID", "Customer ID", "Vehicle Model", "Reserve Date", "Return Date"
            }
        ));
        jScrollPane5.setViewportView(tblReservations);

        txtVehicleId.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 47, -1, 254));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Your Reservations ");
        txtVehicleId.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 130, 23));

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        txtVehicleId.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 242, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/okcc1.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        txtVehicleId.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 510));

        jTabbedPane1.addTab("", txtVehicleId);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVehicles.setBackground(new java.awt.Color(0, 153, 0));
        tblVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Vehcle ID", "Model", "PlateNo", "MileAge", "DailyPrice", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblVehicles);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 518, 216));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("View Avilable Vehcle");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/okcc1.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 1050, 510));

        jTabbedPane1.addTab("", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setBackground(new java.awt.Color(0, 204, 0));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("Search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        txtModelSearch2.setBackground(new java.awt.Color(0, 153, 0));
        txtModelSearch2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtModelSearch2.setForeground(new java.awt.Color(0, 0, 0));
        txtModelSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelSearch2ActionPerformed(evt);
            }
        });
        jPanel4.add(txtModelSearch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 200, -1));

        SearchTbl.setBackground(new java.awt.Color(0, 204, 0));
        SearchTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "VehicleId", "Model", "PlateNo", "MileAge", "DailyPrice", "Status"
            }
        ));
        jScrollPane2.setViewportView(SearchTbl);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 594, 110));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Enter Vehicle Name ");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 200, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/okcc1.png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 970, 500));

        jTabbedPane1.addTab("", jPanel4);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Reserve");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 214, 124, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Return Date");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 90, 22));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Reserve Date");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 109, -1));

        txtReturnDate.setBackground(new java.awt.Color(0, 204, 51));
        txtReturnDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtReturnDate.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(txtReturnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 79, 151, -1));

        txtReserveDate.setBackground(new java.awt.Color(0, 204, 0));
        txtReserveDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtReserveDate.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(txtReserveDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 39, 151, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Vihecle Id");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 142, 109, -1));

        txtVehId.setBackground(new java.awt.Color(0, 204, 51));
        txtVehId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtVehId.setForeground(new java.awt.Color(0, 0, 0));
        txtVehId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehIdActionPerformed(evt);
            }
        });
        jPanel6.add(txtVehId, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 139, 151, -1));

        reservation.setBackground(new java.awt.Color(0, 204, 0));
        reservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Vehicle ID", "Model", "PlateNo", "MileAge", "DailyPrice", "Status"
            }
        ));
        jScrollPane4.setViewportView(reservation);

        jPanel6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 48, 387, 254));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/okcc1.png"))); // NOI18N
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 950, 510));

        jTabbedPane1.addTab("", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
        loadAvailableVehiclesCustomer();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
        loadReservations1();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();

    // Open Login Page
    LoginView login = new LoginView();
    login.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

  public void loadVehicles() {
    VehicleController controller = new VehicleController();
     
    ArrayList<Vehicle> vehicles = (ArrayList<Vehicle>) controller.getAllVehicles();
           
    DefaultTableModel model = (DefaultTableModel) tblVehicles.getModel();
            
    model.setRowCount(0);

    for (Vehicle v : vehicles) {

        model.addRow(new Object[] {

            v.getVehId(),
            v.getModel(),
            v.getPlateNo(),
            v.getMileAge(),
            v.getDailyPrice(),
            v.getAvailability()

        });
    }}
   public void loadAvilableVehicles() {
    VehicleController controller = new VehicleController();
     
    ArrayList<Vehicle> vehicles = (ArrayList<Vehicle>) controller.GetavilableVehicle();
           
    DefaultTableModel model = (DefaultTableModel) tblVehicles.getModel();
            
    model.setRowCount(0);

    for (Vehicle v : vehicles) {

        model.addRow(new Object[] {

            v.getVehId(),
            v.getModel(),
            v.getPlateNo(),
            v.getMileAge(),
            v.getDailyPrice(),
            v.getAvailability()

        });
    }}
   public void loadVehiclesID(int vehicleId) {
    VehicleController controller = new VehicleController();

    Vehicle v = controller.getVehicleById(vehicleId);

    DefaultTableModel model = (DefaultTableModel) SearchTbl.getModel();

    model.setRowCount(0);

    if (v != null) {

        model.addRow(new Object[]{
            v.getVehId(),
            v.getModel(),
            v.getPlateNo(),
            v.getMileAge(),
            v.getDailyPrice(),
            v.getAvailability()
        });

    } else {
        JOptionPane.showMessageDialog(this, "Vehicle not found!");
    }}
   public void loadVehiclesByModel1(String model) {

    VehicleController controller = new VehicleController();

    List<Vehicle> vehicles = controller.getVehiclesByModel(model);

    DefaultTableModel modelTable =
            (DefaultTableModel) SearchTbl.getModel();

    modelTable.setRowCount(0);

    for (Vehicle v : vehicles) {

        modelTable.addRow(new Object[]{
            v.getVehId(),
            v.getModel(),
            v.getPlateNo(),
            v.getMileAge(),
            v.getDailyPrice(),
            v.getAvailability()
        });
    }
}
   public void loadVehiclesByModel(String model) {

    VehicleController controller = new VehicleController();

    List<Vehicle> vehicles = controller.getVehiclesByModel(model);

    DefaultTableModel modelTable = (DefaultTableModel) tblVehicles1.getModel();

    modelTable.setRowCount(0);

    for (Vehicle v : vehicles) {

        modelTable.addRow(new Object[]{
            v.getVehId(),
            v.getModel(),
            v.getPlateNo(),
            v.getDailyPrice(),
            v.getAvailability()
        });
    }
}
   public void loadAvailableVehiclesCustomer(){
       VehicleController controller = new VehicleController();

    List<Vehicle> vehicles = controller.GetavilableVehicle();

    DefaultTableModel model = (DefaultTableModel) reservation.getModel();

    model.setRowCount(0);

    for (Vehicle v : vehicles) {

        model.addRow(new Object[]{
            v.getVehId(),
            v.getModel(),
            v.getPlateNo(),
            v.getMileAge(),
            v.getDailyPrice(),
            v.getAvailability()
        });
    }}

   private void loadReservations1() {

    ReservationController controller =  new ReservationController();

    VehicleDAO vehicleDAO = new VehicleDAO();

    List<Reservation> list =
            controller.getAllReservations();

    DefaultTableModel model =
            (DefaultTableModel) tblReservations.getModel();

    model.setRowCount(0);

    for (Reservation r : list) {

        String vehicleModel =
                vehicleDAO.getVehicleModel(
                        r.getVehId());

        model.addRow(new Object[]{

            r.getReservationId(),
            r.getCustomerId(),
            vehicleModel,
            r.getReserveDate(),
            r.getReturnDate()

        });
    }
}
      
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton6ActionPerformed
  public void loadReservationsforCustomer() {

    int customerId =
            Session.getCurrentUserId();

    ReservationController controller =
            new ReservationController();

    List<Reservation> reservations =
            controller.getReservationsByCustomerId(
                    customerId);

    DefaultTableModel model =
            (DefaultTableModel)
            tblReservations.getModel();

    model.setRowCount(0);

    for (Reservation r : reservations) {

        model.addRow(new Object[]{

            r.getReservationId(),
            r.getVehId(),
            r.getReserveDate(),
            r.getReturnDate()
            

        });
    }
}
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:

    int vehId = Integer.parseInt(txtVehicleModel.getText());

ReservationController controller = new ReservationController();
controller.cancelReservationByVehId(vehId);

JOptionPane.showMessageDialog(this, "Cancelled Successfully");

loadReservations1();
loadVehicles();     // refresh vehicles list
    }//GEN-LAST:event_jButton11ActionPerformed

    private void txtVehIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehIdActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int vehId = Integer.parseInt(txtVehId.getText());
        int customerId = Session.getCurrentUserId();

        String reserveDate = txtReserveDate.getText();
        String returnDate = txtReturnDate.getText();

        ReservationController controller = new ReservationController();

controller.reserveVehicle(customerId, vehId, reserveDate, returnDate);

JOptionPane.showMessageDialog(this, "Vehicle Reserved Successfully!");
loadAvailableVehiclesCustomer();

        JOptionPane.showMessageDialog(this, "Vehicle Reserved Successfully!");

        loadAvailableVehiclesCustomer(); // refresh table
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        VehicleController controller =new VehicleController();
        String model = txtModelSearch1.getText().trim();

        if (model.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter model name!");
            return;
        }

        loadVehiclesByModel(model);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void txtModelSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelSearch1ActionPerformed

    private void txtModelSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelSearch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelSearch2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
          VehicleController controller =new VehicleController();
        String model = txtModelSearch2.getText().trim();

        if (model.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter model name!");
            return;
        }

        loadVehiclesByModel1(model);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        loadAvilableVehicles();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtVehicleModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleModelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(CustomerDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SearchTbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable reservation;
    private javax.swing.JTable tblReservations;
    private javax.swing.JTable tblVehicles;
    private javax.swing.JTable tblVehicles1;
    private javax.swing.JTextField txtModelSearch1;
    private javax.swing.JTextField txtModelSearch2;
    private javax.swing.JTextField txtReserveDate;
    private javax.swing.JTextField txtReturnDate;
    private javax.swing.JTextField txtVehId;
    private javax.swing.JPanel txtVehicleId;
    private javax.swing.JTextField txtVehicleModel;
    // End of variables declaration//GEN-END:variables
}
