/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.CustomerController;
import Controller.ReservationController;
import Controller.VehicleController;
import DAO.VehicleDAO;
import Model.Customer;
import Model.Reservation;
import Model.Vehicle;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kaleb
 */
public class EmployeeDashboard extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeDashboard
     */
    public EmployeeDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblPlateNo = new javax.swing.JLabel();
        lblMileage = new javax.swing.JLabel();
        lblDailyPrice = new javax.swing.JLabel();
        lblAvailability = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblVehicles = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();
        btnViewCustomers = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtVehicleId = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnTotalVehicles = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblReservations2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        txtPlateNo = new javax.swing.JTextField();
        txtMileage = new javax.swing.JTextField();
        txtDailyPrice = new javax.swing.JTextField();
        txtAvailability = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        selectedVehicleId = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Vehicle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 57, 156, 35));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update Vehicle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 156, 35));

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Delete Vihecle");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 124, 156, 43));

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("View Total Vehicles");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 276, 156, 35));

        jPanel12.setBackground(new java.awt.Color(153, 0, 0));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTextPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTextPane1);

        jPanel12.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 30, 207, -1));

        jTextPane2.setBackground(new java.awt.Color(0, 0, 0));
        jTextPane2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jTextPane2);

        jPanel12.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 81, 207, -1));

        jTextPane3.setBackground(new java.awt.Color(0, 0, 0));
        jTextPane3.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(jTextPane3);

        jPanel12.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 133, 207, -1));

        jTextPane4.setBackground(new java.awt.Color(0, 0, 0));
        jTextPane4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextPane4.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(jTextPane4);

        jPanel12.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 184, 207, -1));

        jTextPane5.setBackground(new java.awt.Color(0, 0, 0));
        jTextPane5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextPane5.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane5.setViewportView(jTextPane5);

        jPanel12.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 231, 207, -1));

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Add Vihecle");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 130, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vihecle Model");
        jPanel12.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 110, 24));

        lblPlateNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPlateNo.setForeground(new java.awt.Color(255, 255, 255));
        lblPlateNo.setText("Plate Number");
        jPanel12.add(lblPlateNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 90, -1));

        lblMileage.setBackground(new java.awt.Color(255, 255, 255));
        lblMileage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMileage.setForeground(new java.awt.Color(255, 255, 255));
        lblMileage.setText("MileAge");
        jPanel12.add(lblMileage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 81, -1));

        lblDailyPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDailyPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblDailyPrice.setText("DailyPrice");
        jPanel12.add(lblDailyPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 67, -1));

        lblAvailability.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAvailability.setForeground(new java.awt.Color(255, 255, 255));
        lblAvailability.setText("Status");
        jPanel12.add(lblAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 67, 26));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("", jPanel2);

        jPanel5.setBackground(new java.awt.Color(204, 0, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVehicles.setBackground(new java.awt.Color(102, 0, 0));
        tblVehicles.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblVehicles.setForeground(new java.awt.Color(255, 255, 255));
        tblVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Vehicle ID", "Model", "Plate No", "MileAge", "Daily Price", "Status"
            }
        ));
        jScrollPane7.setViewportView(tblVehicles);

        jPanel5.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 427, 163));

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("View All");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 175, 35));

        jTabbedPane1.addTab("", jPanel5);

        jPanel6.setBackground(new java.awt.Color(204, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCustomers.setBackground(new java.awt.Color(102, 0, 0));
        tblCustomers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblCustomers.setForeground(new java.awt.Color(255, 255, 255));
        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane8.setViewportView(tblCustomers);

        jPanel6.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 27, 464, 247));

        btnViewCustomers.setBackground(new java.awt.Color(0, 0, 0));
        btnViewCustomers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViewCustomers.setForeground(new java.awt.Color(255, 255, 255));
        btnViewCustomers.setText("View Customer's");
        btnViewCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCustomersActionPerformed(evt);
            }
        });
        jPanel6.add(btnViewCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 334, 150, -1));

        jTabbedPane1.addTab("", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("", jPanel7);

        jPanel10.setBackground(new java.awt.Color(153, 0, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Customer's");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 42, 140, -1));

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("View Total Customers");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jTabbedPane1.addTab("", jPanel10);

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel3.setForeground(new java.awt.Color(153, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtVehicleId.setBackground(new java.awt.Color(0, 0, 0));
        txtVehicleId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtVehicleId.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane6.setViewportView(txtVehicleId);

        jPanel3.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 49, 158, 33));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Vehicle ID");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 49, 144, 33));

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Delete");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 134, 97, -1));

        jTabbedPane1.addTab("", jPanel3);

        jPanel9.setBackground(new java.awt.Color(153, 0, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Vehicles");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 95, -1));

        btnTotalVehicles.setBackground(new java.awt.Color(0, 0, 0));
        btnTotalVehicles.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTotalVehicles.setText("Get Total Vihecles");
        btnTotalVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalVehiclesActionPerformed(evt);
            }
        });
        jPanel9.add(btnTotalVehicles, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 97, -1, -1));

        jTabbedPane1.addTab("", jPanel9);

        jPanel8.setBackground(new java.awt.Color(153, 0, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton14.setBackground(new java.awt.Color(0, 0, 0));
        jButton14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("View All Reservations");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 237, -1, 40));

        tblReservations2.setBackground(new java.awt.Color(102, 0, 0));
        tblReservations2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblReservations2.setForeground(new java.awt.Color(255, 255, 255));
        tblReservations2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Reservation ID", "Customer ID", "Vehicle ID", "Reserve Date", "Return Date"
            }
        ));
        jScrollPane10.setViewportView(tblReservations2);

        jPanel8.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 416, 164));

        jTabbedPane1.addTab("", jPanel8);

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Model");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 62, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("plateNo");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 163, 62, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mileage");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 218, 62, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dailyprice");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 269, 62, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Avilablity");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 318, 62, -1));

        txtModel.setBackground(new java.awt.Color(0, 0, 0));
        txtModel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtModel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 111, 183, -1));

        txtPlateNo.setBackground(new java.awt.Color(0, 0, 0));
        txtPlateNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPlateNo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txtPlateNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 160, 183, -1));

        txtMileage.setBackground(new java.awt.Color(0, 0, 0));
        txtMileage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMileage.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txtMileage, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 215, 183, -1));

        txtDailyPrice.setBackground(new java.awt.Color(0, 0, 0));
        txtDailyPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtDailyPrice.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txtDailyPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 266, 183, -1));

        txtAvailability.setBackground(new java.awt.Color(0, 0, 0));
        txtAvailability.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAvailability.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txtAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 315, 183, -1));

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Update");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 377, 142, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Vihecle Id");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 61, 84, -1));

        selectedVehicleId.setBackground(new java.awt.Color(0, 0, 0));
        selectedVehicleId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selectedVehicleId.setForeground(new java.awt.Color(255, 255, 255));
        selectedVehicleId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedVehicleIdActionPerformed(evt);
            }
        });
        jPanel4.add(selectedVehicleId, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 58, 183, -1));

        jTabbedPane1.addTab("", jPanel4);

        jPanel14.setBackground(new java.awt.Color(102, 0, 0));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("View All Customers");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("View Reservations");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("View Total Customers");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("View all Vehicle’s ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(0, 0, 0));
        jButton16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("LogOut");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton16))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton16)
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel11)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void loadCustomers() {

    CustomerController controller =
            new CustomerController();

    List<Customer> customers =
            controller.getAllCustomers();

    DefaultTableModel model =
            (DefaultTableModel) tblCustomers.getModel();

    model.setRowCount(0);

    for (Customer c : customers) {

        model.addRow(new Object[]{

            c.getCustomerId(),
            c.getFirstName(),
            c.getLastName(),
            c.getCity(),
            c.getCountry(),
            c.getContactNumber(),
            c.getLicenseNumber()

        });
    }
}
 private void loadReservations1() {

    ReservationController controller =
            new ReservationController();

    VehicleDAO vehicleDAO =
            new VehicleDAO();

    List<Reservation> list =
            controller.getAllReservations();

    DefaultTableModel model =
            (DefaultTableModel) tblReservations2.getModel();

    model.setRowCount(0);

    for (Reservation r : list) {

        String vehicleModel =
                vehicleDAO.getVehicleModel(
                        r.getVehId());

        model.addRow(new Object[]{

            r.getReservationId(),
            r.getCustomerId(),
            vehicleModel,
            r.getReserveDate(),
            r.getReturnDate()

        });
    }}
    public void loadVehicles() {
    VehicleController controller = new VehicleController();
     
    ArrayList<Vehicle> vehicles = (ArrayList<Vehicle>) controller.getAllVehicles();
           
    DefaultTableModel model = (DefaultTableModel) tblVehicles.getModel();
            
    model.setRowCount(0);

    for (Vehicle v : vehicles) {

        model.addRow(new Object[] {

            v.getVehId(),
            v.getModel(),
            v.getPlateNo(),
            v.getMileAge(),
            v.getDailyPrice(),
            v.getAvailability()

        });
    }}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTabbedPane1.setSelectedIndex(8);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       jTabbedPane1.setSelectedIndex(1);
       CustomerDashBoard C = new CustomerDashBoard();
       C.loadAvilableVehicles();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTabbedPane1.setSelectedIndex(7);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        loadReservations1();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:

        int vehicleId = Integer.parseInt(txtVehicleId.getText());

        VehicleController controller = new VehicleController();
        controller.deleteVehicle(vehicleId);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnViewCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCustomersActionPerformed
        // TODO add your handling code here:
        loadCustomers();
    }//GEN-LAST:event_btnViewCustomersActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        loadVehicles();
    }//GEN-LAST:event_jButton13ActionPerformed

//private void loadVehicles() {
//
//    VehicleController controller = new VehicleController();
//
//    ArrayList<Vehicle> vehicles = (ArrayList<Vehicle>) controller.getAllVehicles();
//
//    DefaultTableModel model = (DefaultTableModel) tblVehicles.getModel();
//
//    model.setRowCount(0);
//
//    for (Vehicle v : vehicles) {
//
//        model.addRow(new Object[]{
//            v.getVehId(),
//            v.getModel(),
//            v.getPlateNo(),
//            v.getMileAge(),
//            v.getDailyPrice(),
//            v.getAvailability()
//        });
//    }
//}
    private void selectedVehicleIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedVehicleIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedVehicleIdActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        Vehicle vehicle = new Vehicle();

        vehicle.setVehId(Integer.parseInt(selectedVehicleId.getText()));
        vehicle.setModel(txtModel.getText());
        vehicle.setPlateNo(txtPlateNo.getText());
        vehicle.setMileAge(Integer.parseInt(txtMileage.getText()));
        vehicle.setDailyPrice(Double.parseDouble(txtDailyPrice.getText()));
        vehicle.setAvailability(txtAvailability.getText());
        VehicleController controller = new VehicleController();
        controller.updateVehicle(vehicle);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       try {
    // READ INPUTS
    String model = jTextPane1.getText().trim();
    String plate = jTextPane2.getText().trim();
    String mileageText = jTextPane3.getText().trim();
    String priceText = jTextPane4.getText().trim();
    String availability = jTextPane5.getText().trim();

    
    if (model.isEmpty() || plate.isEmpty() || mileageText.isEmpty()
            || priceText.isEmpty() || availability.isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
            null,
            "⚠ Please fill all fields!",
            "Missing Data",
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

   
    int mileage = Integer.parseInt(mileageText);
    double price = Double.parseDouble(priceText);

    // CREATE VEHICLE OBJECT
    Vehicle vehicle = new Vehicle(
        0,
        model,
        plate,
        mileage,
        price,
        availability
    );

    VehicleController controller = new VehicleController();
    controller.addVehicle(vehicle);

    // SUCCESS MESSAGE
    javax.swing.JOptionPane.showMessageDialog(
        null,
        "✔ Vehicle Added Successfully!",
        "Success",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );

} catch (NumberFormatException e) {

    javax.swing.JOptionPane.showMessageDialog(
        null,
        "❌ Mileage and Price must be numbers!",
        "Input Error",
        javax.swing.JOptionPane.ERROR_MESSAGE
    );

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(
        null,
        "Unexpected error: " + e.getMessage(),
        "Error",
        javax.swing.JOptionPane.ERROR_MESSAGE
    );
}
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnTotalVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalVehiclesActionPerformed
        // TODO add your handling code here:
        VehicleController controller =
            new VehicleController();

    int total =
            controller.getTotalVehicles();

    JOptionPane.showMessageDialog(
            this,
            "Total Vehicles = " + total);
    }//GEN-LAST:event_btnTotalVehiclesActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
           CustomerController controller =
            new CustomerController();
           int total = controller.getTotalCustomers();

    JOptionPane.showMessageDialog(
            this,
            "Total Customers = " + total);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
          this.dispose();

    // Open Login Page
    LoginView login = new LoginView();
    login.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTotalVehicles;
    private javax.swing.JButton btnViewCustomers;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblDailyPrice;
    private javax.swing.JLabel lblMileage;
    private javax.swing.JLabel lblPlateNo;
    private javax.swing.JTextField selectedVehicleId;
    private javax.swing.JTable tblCustomers;
    private javax.swing.JTable tblReservations2;
    private javax.swing.JTable tblVehicles;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtDailyPrice;
    private javax.swing.JTextField txtMileage;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPlateNo;
    private javax.swing.JTextPane txtVehicleId;
    // End of variables declaration//GEN-END:variables
}
